# ================ TI ================

TI_I2C_WADDR = 0x34
TI_I2C_RADDR = 0x35

TI_REG_R_TESTIMAGE = 0x00
TI_REG_W_TESTIMAGE = 0x80

TI_REG_R_FLIP_LONG = 0x08
TI_REG_W_FLIP_LONG = 0x88

TI_REG_R_FLIP_SHORT = 0x09
TI_REG_W_FLIP_SHORT = 0x89

TI_REG_R_TRIGGER_OUT1 = 0x6A
TI_REG_W_TRIGGER_OUT1 = 0xEA

TI_REG_R_SEQUENCE = 0x65
TI_REG_W_SEQUENCE = 0xE5

TI_SEQUENCE_ON = 0x2
TI_SEQUENCE_OFF = 0x0
TI_SEQUENCE_PAUSE = 0x1

TI_REG_R_INVERT_DATA = 0x74
TI_REG_W_INVERT_DATA = 0xF4

TI_REG_R_IT6535 = 0x0C
TI_REG_W_IT6535 = 0x8C

TI_IT6536_OFF = 0x0
TI_IT6536_HDMI = 0x1
TI_IT6536_DISPLAY = 0x2

TI_REG_R_IT6535 = 0x0C
TI_REG_W_IT6535 = 0x8C

TI_REG_R_TEST_PATTERN = 0x0A
TI_REG_W_TEST_PATTERN = 0x8A

TI_REG_R_DISPLAY_MODE = 0x69
TI_REG_W_DISPLAY_MODE = 0xE9

TI_DISPLAY_MODE_NORMAL = 0x0
TI_DISPLAY_MODE_PRE_STORED = 0x1
TI_DISPLAY_MODE_VIDEO_PATTERN = 0x2
TI_DISPLAY_MODE_ON_THE_FLY = 0x3

TI_REG_R_ERROR_CODE = 0x32

TI_REG_R_PATTERN_DISPLAY_LUT_CONFIG = 0x75
TI_REG_W_PATTERN_DISPLAY_LUT_CONFIG = 0xF5
# Bit 0-10 = Numer of LUT entries
# 15:11 reserved
# 16:47 Number of times to repeat pattern sequence  0=forever

TI_REG_W_PATTERN_DISPLAY_LUT = 0xF8

TI_REG_R_PIXEL_MODE = 0X03
TI_REG_W_PIXEL_MODE = 0X83

TI_REG_R_MAIN_STATUS = 0x22

# ================ Visitech ================

LED_I2C_WADDR = 0x44
LED_I2C_RADDR = 0x45
LED_AMPLITUDE_REGISTER = 0x14
LED_TEST_REGISTER = 0x340
LED_SV_UPDATE_REGISTER = 0x10

LED_PFACTOR_REGISER = 0x24
LED_IFACTOR_REGISTER = 0x28
LED_OCPVALUE_REGISTER = 0x4C
LED_OPPVALUE_REGISTER = 0x54
LED_PWM_KEEP_OFF_REGISTER = 0x78
LED_BOARD_TEMP_LIMIT_REGISTER = 0x378
LED_LED_TEMP_LIMIT_REGISTER = 0x80

LED_BOARDTEMP_REGISTER = 0x370
LED_LEDTEMP_REGISTER = 0x34

LED_STICKYBITS_REGISTER = 0x358
# Sticky bits: (4:OCP (3: Door_open (2: Fan stopped (1: Board_overtemp, (0: LED_overtemp
# Power mode

NUM_SEQUENCE_COMMAND_VAR = 7
MAX_NUM_PATTERNS_IN_SEQ = 512
OCP_AMP_PER_UNIT_HW_VER1 = 0.196

# Defualt values to initialize LED
DEF_PWM_KEEP_OFF = 1
DEF_PFACTOR = 100
DEF_IFACTOR = 25
DEF_LED_TEMP_LIMIT = 400
DEF_BOARD_TEMP_LIMIT = 70
# DEF_LED_TEMP_LIMIT = 1000    # ?? LED temp limit: 50 deg C
# DEF_BOARD_TEMP_LIMIT = 90    # ?? Board temp limit: 70 deg C

# Default OCP value
DEF_OCP_AMP = 20

# Default OPP values for different hardware versions
DEF_OPP_HW_VER_1 = 275