ERROR_OK = 0
ERROR_DLN_ADAPTER_OPEN = 1
ERROR_GET_I2C_PORT_COUNT = 2
ERROR_NO_I2C_PORTS = 3
ERROR_DLN_SERVER_CONNECT_FAILED = 4
ERROR_MASTER_SET_FREQUENCY_FAILED = 5
WARNING_FREQUENCY_ROUNDED = 6
ERROR_GET_FREQUENCY_FAILED = 7
ERROR_MASTER_ENABLE_FAILED = 8
ERROR_MASTER_DISABLE_FAILED = 9
ERROR_MASTER_SCAN_FAILED = 10
ERROR_MASTER_IS_ENABLED_FAILED = 11
ERROR_SET_REPLY_COUNT_FAILED = 12
ERROR_GET_REPLY_COUNT = 13
ERROR_UNVALID_INPUT = 14
ERROR_READ_FAILED = 15
ERROR_WRITE_FAILED = 16
ERROR_INVALID_WRITE_DATA = 17
ERROR_SEQUENCE_TO_MANY_PATTERNS = 18
ERROR_COULD_NOT_FIND_SEQUENCE_FILE = 19
ERROR_COULD_NOT_FIND_ANY_LINES_IN_SEQUENCE_FILE = 20
ERROR_MISSING_ARGUMENTS = 21
ERROR_COMMAND_ARGUMENT_MISMATCH = 22
ERROR_TO_HIGH_IMAGE_NUM = 23
ERROR_TO_HIGH_LED_AMPLITUDE = 24

ERROR_SEQUENCE_NUM_ARGS = 1000
ERROR_SEQUENCE_VALUES = 0x10000
# LAST HEX DIGIT IS ARGUMENT NUM, hex digit 3,2,1 is line num

LED_TEMP_RETURN_BASE = 2000
LED_BOARD_TEMP_RETURN_BASE = 3000
LED_STICKY_RETURN_BASE = 4000
TI_SEQUENCE_RETURN_BASE = 5000
# Sticky bits: (4):OCP (3): Door_open (2): Fan stopped (1): Board_overtemp, (0): LED_overtemp